services:
  redis:
    image: redis:7-alpine
    container_name: holt-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
